[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12.4.0"
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=250000"
[[redirects]]
  from = "https://www.free2betherapy.co.uk/*"
  to = "https://www.free2betherapy.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://free2betherapy.co.uk/*"
  to = "https://www.free2betherapy.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://free2betherapy.netlify.com/*"
  to = "https://www.free2betherapy.com/:splat"
  status = 301
  force = true